"create mini": {
    "prefix": "makemini",
    "body": [
      "#!/usr/bin/env rust-script",
      "//! TODO: ${1:Description Here}",
      "//!",
      "//! Copyright CURRENT_YEAR, ${2:Evan Boehs}",
      "//!",
      "//! ```cargo",
      "//! [package]",
      "//! name = \"$TM_FILENAME_BASE\"",
      "//! authors/*  */ = [\"${3:Evan Boehs}\"]",
      "//! version = \"${4:0.1.0}\"",
      "//! license = \"${5:Commons Clause Apache-2.0}\"",
      "//! edition = \"${6:2018}\"",
      "//!",
      "//! [dependencies]",
      "//! gumdrop = \"0.8\"",
      "//! ```",
      "#![forbid(unsafe_code)]",
      "",
      "use std::path::PathBuf;",
      "use gumdrop::Options;",
      "",
      "#[derive(Debug, Options)]",
      "struct MyOptions {",
      "    // NOTE: This will panic on paths containing invalid UTF-8",
      "    #[options(free)]",
      "    inpath: Vec<String>,",
      "",
      "    #[options(help = \"print help message\")]",
      "    help: bool,",
      "}",
      "",
      "fn main() {",
      "    let opts = MyOptions::parse_args_default_or_exit();",
      "",
      "    todo!();",
      "    ${0}",
      "}",
      "",
      "// vim: set ft=rust sw=4 sts=4 expandtab :"
    ],
    "description": "Make mini program"
  }